# Enable File Sharing through firewall
Set-NetfirewallRule -Name "FPS-SMB-In-TCP" -Enabled True

# Fallback / Debug - Enable all File Sharing Services (Bad practice)
$FWRuleNames = @(
'FPSSMBD-iWARP-In-TCP',
'FPS-RPCSS-In-TCP-NoScope',
'FPS-SpoolSvc-In-TCP-NoScope',
'FPS-ICMP6-ERQ-Out-V2',
'FPS-ICMP6-ERQ-Out-V2_1',
'FPS-NB_Session-In-TCP-NoScope',
'FPS-NB_Datagram-Out-UDP-NoScope',
'FPS-SpoolSvc-In-TCP',
'FPS-ICMP4-ERQ-Out',
'FPS-NB_Name-Out-UDP-NoScope',
'FPS-SMB-Out-TCP',
'FPS-ICMP4-ERQ-Out-NoScope',
'FPS-SMB-Out-TCP-NoScope',
'FPS-SMB-In-TCP-V2',
'FPS-SMB-In-TCP-V2_1',
'FPS-SpoolWorker-In-TCP',
'FPS-NB_Datagram-In-UDP-NoScope',
'FPS-NB_Name-In-UDP',
'FPS-NB_Session-Out-TCP',
'FPS-LLMNR-In-UDP-V2',
'FPS-LLMNR-In-UDP-V2_1',
'FPS-LLMNR-Out-UDP-V2',
'FPS-LLMNR-Out-UDP-V2_1',
'FPS-RPCSS-In-TCP',
'FPS-ICMP6-ERQ-Out',
'FPS-NB_Name-In-UDP-NoScope',
'FPS-SpoolSvc-In-TCP-V2',
'FPS-SpoolSvc-In-TCP-V2_1',
'FPS-NB_Session-In-TCP',
'FPS-ICMP4-ERQ-In',
'FPS-SpoolWorker-In-TCP-V2',
'FPS-SMB-In-TCP',
'FPS-SMB-Out-TCP-V2',
'FPS-SMB-Out-TCP-V2_1',
'FPS-SMB-In-TCP-NoScope',
'FPS-ICMP6-ERQ-Out-NoScope',
'FPS-SpoolWorker-In-TCP-NoScope',
'FPS-ICMP4-ERQ-In-V2',
'FPS-ICMP4-ERQ-In-V2_1',
'FPS-NB_Datagram-Out-UDP',
'FPS-NB_Session-Out-TCP-NoScope',
'FPS-ICMP6-ERQ-In',
'FPS-ICMP4-ERQ-Out-V2',
'FPS-ICMP4-ERQ-Out-V2_1',
'FPS-RPCSS-In-TCP-V2',
'FPS-RPCSS-In-TCP-V2_1',
'FPS-ICMP6-ERQ-In-NoScope',
'FPS-NB_Name-Out-UDP',
'FPS-NB_Datagram-In-UDP',
'FPS-ICMP4-ERQ-In-NoScope',
'FPS-LLMNR-In-UDP',
'FPS-LLMNR-Out-UDP',
'FPS-ICMP6-ERQ-In-V2',
'FPS-ICMP6-ERQ-In-V2_1' );

Foreach ($n in $FWRuleNames)
{
  Set-NetFirewallRule -Name $n -Enabled True;
}